export const PdfProcessingConstants = {
  LOGS: {
    ERROR_PROCESSING_PDF: 'ERROR_PROCESSING_PDF',
    PRELIMINARY_DATA_EXTRACTED: 'PRELIMINARY_DATA_EXTRACTED',
    PDF_PROCESSING_COMPLETE: 'PDF_PROCESSING_COMPLETE',
    PDF_QUEUED: 'PDF_QUEUED'
  }
}; 